<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;


/**
 * Site controller
 */
class BaseController extends Controller
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
