<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use app\common\CommonClass;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        //当没有传递任何参数的时候
        return true;
    }
}

?>