<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;

class BaseController extends Controller
{
     public function beforeAction($action)
     {
         return parent::beforeAction($action); // TODO: Change the autogenerated stub
         return true;
     }
}

?>