<?php

namespace frontend\controllers;

use Yii;
use app\common\CommonClass;
use yii\web\Controller;


/**
 * 公用功能登录注册 都在这里
 * Class PublicController
 * @package frontend\controllers
 */
class PublicController extends Controller
{
    //每个控制器的基本信息
    public $basics;

    public function beforeAction($action)
    {
        $this->basics = CommonClass::get_basics_info();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    

    public function actionIndex()
    {

        return $this->render('index');
    }

    public function actionLogin()
    {

        return $this->render('login');
    }
}

?>