<?php

namespace frontend\controllers;

use Yii;
use app\common\CommonClass;
use yii\web\Controller;
use app\models\ecs\ecs_nav;
use ciniran\excel;


/**
 * 公用功能登录注册 都在这里
 * Class PublicController
 * @package frontend\controllers
 */
class PublicController extends Controller
{
    //每个控制器的基本信息
    public $basics;

    public function beforeAction($action)
    {
        $this->basics = CommonClass::get_basics_info();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * 登录
     * @return string
     */
    public function actionLogin()
    {
        return $this->render('login');
    }


    /**
     * 注册
     * @return string
     */
    public function actionReg()
    {
        return $this->render('reg');
    }

    /**
     * 视频设备
     * @return string
     *
     */
    public function actionVideo(){
        return $this->render('video');
    }
}

?>