<?php

namespace api\controllers;
use Yii;
use api\common\CommonClass;
use yii\rest\ActiveController;


/**
 */
class BaseActiveController extends ActiveController
{
    public $data;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {    
        parent::actions();
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        return true;
    }
}