<?php

namespace api\controllers;
use Yii;
use api\common\CommonClass;
use yii\rest\ActiveController;


/**
 */
class BaseActiveController extends ActiveController
{
    public $data;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {    
        parent::actions();
    }

    public function beforeAction($action)
    {

        parent::beforeAction($action); // TODO: Change the autogenerated stub
        return true;
    }

    public function afterAction($action, $result)
    {    $logger_data = Yii::getLogger()->getProfiling();
        print_r($logger_data);
        die("111");
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
//    public function afterAction($action, $result)
//    {
//        // 超过3秒发送警告
//        $logger_data = Yii::getLogger()->getProfiling();
//        var_dump($action);
//        //排除批改页面，里面接口+sql语句比较多task|exam
//        if (!in_array($action->controller->id, ['task','exam']) && array_sum(array_column($logger_data, 'duration')) * 1000 > Yii::$app->params['request_time_out']) {
//            $return_logger['Url'] = $action->controller->id . '/' . $action->id;
//            $return_logger['Info'] = array_column($logger_data, 'info');
//            $return_logger['Category'] = array_column($logger_data, 'category');
//            $return_logger['Duration'] = array_map(function($v){return $v*1000;}, array_column($logger_data, 'duration'));
//            $return_logger['TotalDuration'] = array_sum(array_column($logger_data, 'duration')) * 1000;
//            CommonClass::ErrorSendMail('运行时间超过了三秒',$return_logger);
//
//        }
//
//        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
//    }
}