<?php

namespace api\controllers;

use Yii;
use app\common\CommonClass;
use yii\rest\ActiveController;



/**
 */
class CwjController extends BaseActiveController
{

    public $modelClass = '\common\models\cwj';

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub

    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {

        $actions = parent::actions();
        unset($actions['delete'], $actions['create']);
        $action = [
            //登录接口
            'login' => [
                'class' => 'app\controllers\cwj\LoginAction',
                'modelClass' => $this->modelClass
            ],
            'reg'=>[
                'class' => 'app\controllers\cwj\RegAction',
                'modelClass' => $this->modelClass
            ],
            'check'=>[
                'class' => 'app\controllers\cwj\CheckAction',
                'modelClass' => $this->modelClass
            ]
        ];
        return $action;

    }

    public function beforeAction($action)
    {
        parent::beforeAction($this->action);

//        //白名单
//        if(YII_ENV == 'prod' && !in_array(Yii::$app->request->getUserIP(), self::IP_WHITE_LIST)) {
//            throw new BadRequestHttpException('Not allowed access', 403);
//        }
        return true;
    }
    

}