<?php

namespace api\controllers;

use Yii;
use app\common\CommonClass;
use yii\rest\ActiveController;
use yii\helpers\ArrayHelper;



/**
 */
class CwjController extends ActiveController
{

    public $modelClass = '\common\models\Cwj';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {

        $actions = parent::actions();
        unset($actions['delete'], $actions['create']);
        return [
            //登录接口
            'login' => [
                'class' => 'app\controllers\cwj\LoginAction',
                'modelClass' => $this->modelClass
            ],
        ];

    }

    public function beforeAction($action)
    {
        parent::beforeAction($this->action);
        $request = Yii::$app->request;
        $method = strtolower($request->getMethod());
        $data = Yii::$app->request->$method();

        print_r($data);
        die();
//        //白名单
//        if(YII_ENV == 'prod' && !in_array(Yii::$app->request->getUserIP(), self::IP_WHITE_LIST)) {
//            throw new BadRequestHttpException('Not allowed access', 403);
//        }
        return true;
    }

}