<?php

namespace api\controllers;
use app\common\CommonClass;
use Yii;
use yii\rest\ActiveController;
use common\models\Wechat;

/**
 */
class WechatController extends ActiveController
{

    public $modelClass = '\common\models\Wechat';
    public function init()
    {
        CommonClass::ErrorSendMail('看看是否调用',Yii::$app->request->get());
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        
        $actions = parent::actions();
        unset($actions['delete'], $actions['create']);
        return [
            //获取微信token
            'token' => [
                'class' => 'app\controllers\wechat\TokenAction',
                'modelClass' => $this->modelClass
            ],
        ];
    }
    
}