<?php

namespace app\module\wechat\controllers;

use Yii;
use yii\web\Controller;
use app\components\Wechat;


class BaseController extends Controller
{
    public function actionIndex(){
        
    }

    
    public function beforeAction($action)
    {
        $result = Yii::$app->wechat->getOauth2AuthorizeUrl('www.baidu.com');
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        return true;
    }

    
}
